/**
 * Validation and output.
 *
 * The definition is checked against the real `@dicebear/schema` before it is written, so a malformed
 * style fails at build time rather than at render time in a consumer's app. Attribution files are
 * regenerated on every run and committed, which lets CI detect a stale NOTICE by diffing.
 */

import { mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'
import schema from '@dicebear/schema/definition.json' with { type: 'json' }
// The published schema declares draft-07, despite the docs advertising 2020-12 — follow the artifact.
import Ajv from 'ajv'
import type { Definition } from '../definition.ts'
import type { Attribution } from '../sources/licenses.ts'

export class ValidationError extends Error {
  override name = 'ValidationError'
}

/**
 * Throws unless the value satisfies the DiceBear definition schema.
 *
 * Takes `unknown` on purpose: the most valuable thing to run this against is a definition loaded from
 * disk, whose static type proves nothing about the bytes actually committed.
 */
export function validateDefinition(definition: unknown): asserts definition is Definition {
  const ajv = new Ajv({ allErrors: true, strict: false })
  const validate = ajv.compile(schema)

  if (validate(definition)) return

  const details = (validate.errors ?? [])
    .map((error) => `${error.instancePath || '/'} ${error.message ?? 'is invalid'}`)
    .join('\n  - ')
  throw new ValidationError(`Definition failed schema validation:\n  - ${details}`)
}

/**
 * Writes the definition as JSON.
 *
 * Key order is not sorted: it comes from the recipe's own declaration order, which is stable across runs
 * and reads far better in a diff than an alphabetised dump.
 */
export async function writeDefinition(path: string, definition: Definition): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await Bun.write(path, `${JSON.stringify(definition, null, 2)}\n`)
}

/**
 * Writes the machine-readable provenance record.
 *
 * Committing this alongside the definition lets CI verify that ATTRIBUTION.md and NOTICE are current
 * without contacting Iconify — a license check that needs the network is a license check that gets
 * skipped.
 */
export async function writeProvenance(path: string, attributions: readonly Attribution[]): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await Bun.write(path, `${JSON.stringify(attributions, null, 2)}\n`)
}

export function renderAttribution(attributions: readonly Attribution[]): string {
  const lines = [
    '# Attribution',
    '',
    'This file is generated by `bun run forge`. Do not edit it by hand.',
    '',
    'The artwork in this project is derived from the icon sets below. All of them are distributed under',
    'permissive licenses that require no per-use attribution; this file exists to credit the authors and',
    'to record provenance.',
    '',
  ]

  for (const attribution of attributions) {
    lines.push(`## ${attribution.setName} (\`${attribution.prefix}\`)`)
    lines.push('')
    lines.push(`- License: ${attribution.spdx}${attribution.licenseUrl ? ` — ${attribution.licenseUrl}` : ''}`)
    if (attribution.author) {
      lines.push(`- Author: ${attribution.author}${attribution.authorUrl ? ` — ${attribution.authorUrl}` : ''}`)
    }
    lines.push(`- Icons used: ${attribution.icons.map((ref) => `\`${ref}\``).join(', ')}`)
    lines.push('')
  }

  return lines.join('\n')
}

export async function writeAttribution(path: string, attributions: readonly Attribution[]): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await Bun.write(path, renderAttribution(attributions))
}

/**
 * Writes a NOTICE for Apache-2.0 sources, or removes the obligation from the output when none are used.
 * Returns whether a NOTICE was required.
 */
export function renderNotice(attributions: readonly Attribution[]): string {
  const requiring = attributions.filter((attribution) => attribution.requiresNotice)
  if (requiring.length === 0) return ''

  const lines = ['This product includes artwork derived from the following Apache-2.0 licensed works.', '']
  for (const attribution of requiring) {
    lines.push(`${attribution.setName} (${attribution.prefix})`)
    if (attribution.author) lines.push(`Copyright the ${attribution.setName} authors — ${attribution.author}`)
    lines.push(
      `Licensed under the Apache License, Version 2.0${attribution.licenseUrl ? ` — ${attribution.licenseUrl}` : ''}`,
    )
    lines.push('')
  }
  return lines.join('\n')
}

/**
 * Writes a NOTICE for Apache-2.0 sources. When none are in use the file is emptied rather than left
 * behind, because a stale NOTICE claims obligations we no longer have.
 */
export async function writeNotice(path: string, attributions: readonly Attribution[]): Promise<boolean> {
  const notice = renderNotice(attributions)

  if (notice === '') {
    const existing = Bun.file(path)
    if (await existing.exists()) await Bun.write(path, '')
    return false
  }

  await mkdir(dirname(path), { recursive: true })
  await Bun.write(path, notice)
  return true
}
