/**
 * Lifts the kept subset of the upstream `avataaars` definition into `source.g.ts`.
 *
 * Run by hand, not by the build — see the licence note at the top of `lexavataaars.recipe.ts`. The
 * output is committed so the study builds without the upstream package present, and so the exact set of
 * borrowed geometry is legible in a diff rather than hidden behind a dependency.
 *
 *   bun run recipes/lexavataaars/extract.ts <path-to-avataaars.min.json>
 *
 * The keep-lists below are the design decision. Everything absent from them was cut on purpose; the
 * reasoning lives beside each component in the recipe, not here.
 */

const KEEP: Record<string, string[]> = {
  // Hair only. Every hat, band, flower and winter cap is gone, and `hijab` and `turban` were removed on
  // a later scope decision by the project owner.
  top: [
    'bigHair',
    'bob',
    'bun',
    'curly',
    'curvy',
    'dreads',
    'dreads01',
    'fro',
    'longButNotTooLong',
    'miaWallace',
    'shortCurly',
    'shortFlat',
    'shortRound',
    'shortWaved',
    'sides',
    'straight01',
    'straight02',
    'straightAndStrand',
    'theCaesar',
    'theCaesarAndSidePart',
  ],
  // Only the blazer survives, and only as raw material: its shirt body, lapels and lapel-fold shadow are
  // the geometry every garment in `hand.ts` is built on.
  clothes: ['blazerAndShirt'],
  // One brow survives. Twelve of upstream's thirteen tilt: measured by rasterising each shape and
  // reading its MIDLINE, `angry` tilts 3.63, `raisedExcited` 3.81, `sadConcerned` -3.44, and even
  // `default` 2.16. `flatNatural` measures -0.19, which is level to within a fifth of a unit, so it
  // stays — it is upstream's own geometry and it passes the test the others fail.
  eyebrows: ['flatNatural'],
  // `closed` reads as asleep and `side` as evasive. Only the plain pupil survives.
  eyes: ['default'],
  // The only mouth in the source that is not doing an expression.
  mouth: ['serious'],
  nose: ['default'],
  // Sober spectacles only.
  accessories: ['prescription01', 'prescription02', 'round'],
  facialHair: ['beardLight', 'beardMedium', 'moustacheMagnum'],
}

const path = Bun.argv[2]
if (!path) throw new Error('usage: bun run recipes/lexavataaars/extract.ts <avataaars.min.json>')
const def = await Bun.file(path).json()

const body: string[] = []
for (const [component, names] of Object.entries(KEEP)) {
  const variants = def.components[component]?.variants
  if (!variants) throw new Error(`no component ${component}`)
  const picked: Record<string, unknown> = {}
  for (const n of names) {
    if (!variants[n]) throw new Error(`no variant ${component}.${n}`)
    picked[n] = variants[n]
  }
  const { width, height } = def.components[component]
  body.push(
    `export const ${component} = {\n  width: ${width},\n  height: ${height},\n` +
      `  variants: ${JSON.stringify(picked)} as Record<string, { elements: Element[] }>,\n} as const\n`,
  )
}

const header = `/**
 * Geometry lifted verbatim from „Avataaars” by Pablo Stanley, via DiceBear's remix of it.
 *
 * GENERATED by \`recipes/lexavataaars/extract.ts\` — do not hand-edit. Hand-edited and newly drawn
 * geometry lives in \`hand.ts\` instead, so the borrowed set stays exactly identifiable.
 *
 * This file is NOT MIT. See \`LICENCE-RISK.md\` in this directory before doing anything with it.
 */

import type { Element } from '@lexavataaars/forge'

/** Canvas the components below are placed on, in the source's own units. */
export const CANVAS = { width: ${def.canvas.width}, height: ${def.canvas.height} } as const

/** The head, neck and jaw shadow, drawn on the canvas itself rather than as a component. */
export const HEAD_ELEMENTS = ${JSON.stringify(def.canvas.elements.filter((e: { type: string }) => e.type === 'element'))} as Element[]

/** Source palettes, kept so the recipe can state which values it dropped and why. */
export const SOURCE_COLORS = ${JSON.stringify(def.colors)} as Record<string, { values: string[]; notEqualTo?: string[] }>

/** Component placements, copied exactly — registration is the whole reason this fork is viable. */
export const PLACEMENT = ${JSON.stringify(
  Object.fromEntries(
    def.canvas.elements
      .filter((e: { type: string }) => e.type === 'component')
      .map((e: { name: string; attributes: { transform: string } }) => [e.name, e.attributes.transform]),
  ),
)} as Record<string, string>
`

await Bun.write(`${import.meta.dir}/source.g.ts`, `${header}\n${body.join('\n')}`)
console.log('wrote source.g.ts')
