/**
 * Recipe + fetched icons → DiceBear definition.
 *
 * This is the only place that knows how the authoring model maps onto the render format. It stays a pure
 * transformation: `emit` handles validation and I/O.
 */

import type { Component, Definition, Element } from '../definition.ts'
import { normalizeIconBody } from '../normalize/index.ts'
import type { FetchedIcon, IconRef } from '../sources/iconify.ts'
import { type CanvasHelpers, type ComponentSpec, isIconComponent, type Recipe } from './recipe.ts'

const SCHEMA_URL = 'https://cdn.hopjs.net/npm/@dicebear/schema@1/dist/definition.min.json'

export class ComposeError extends Error {
  override name = 'ComposeError'
}

/** Every icon a recipe needs, in a stable order, ready to hand to the fetcher. */
export function iconRefsOf(recipe: Recipe): IconRef[] {
  const refs = new Set<IconRef>()
  for (const spec of Object.values(recipe.components)) {
    if (!isIconComponent(spec)) continue
    for (const ref of Object.values(spec.variants)) refs.add(ref)
  }
  return [...refs].sort()
}

export function compose(recipe: Recipe, icons: readonly FetchedIcon[]): Definition {
  const byRef = new Map(icons.map((icon) => [icon.ref, icon]))
  const components: Record<string, Component> = {}

  for (const [name, spec] of Object.entries(recipe.components)) {
    components[name] = isIconComponent(spec)
      ? buildIconComponent(name, spec, byRef, recipe)
      : buildInlineComponent(spec)
  }

  const helpers = makeHelpers(recipe, components)

  return {
    $schema: SCHEMA_URL,
    $comment: 'Generated by @lexavataaars/forge — edit the recipe, not this file.',
    meta: recipe.meta,
    canvas: {
      width: recipe.canvas.width,
      height: recipe.canvas.height,
      elements: recipe.canvasElements(helpers),
    },
    colors: recipe.colors,
    components,
  }
}

function buildIconComponent(
  name: string,
  spec: Extract<ComponentSpec, { source: 'icons' }>,
  byRef: Map<IconRef, FetchedIcon>,
  recipe: Recipe,
): Component {
  const variants: Component['variants'] = {}
  let width: number | undefined
  let height: number | undefined

  for (const [variantName, ref] of Object.entries(spec.variants)) {
    const icon = byRef.get(ref)
    if (!icon) throw new ComposeError(`Component "${name}" references un-fetched icon "${ref}".`)

    // Variants share one coordinate space, so mixing grid sizes inside a component would silently
    // rescale some of the artwork. An empty variant is exempt: it has no geometry for a grid to govern,
    // and requiring one would mean keeping a blank asset per grid size in use.
    const isEmpty = icon.body.trim() === ''
    if (!isEmpty) {
      width ??= icon.width
      height ??= icon.height
      if (icon.width !== width || icon.height !== height) {
        throw new ComposeError(
          `Component "${name}" mixes icon grids: "${ref}" is ${icon.width}×${icon.height}, ` +
            `earlier variants are ${width}×${height}.`,
        )
      }
    }

    const meta = spec.variantMeta?.[variantName]
    variants[variantName] = {
      elements: normalizeIconBody(icon.body, {
        colorName: spec.colorName,
        strokeWidth: spec.stroke?.width ?? recipe.stroke.width,
        strokeLinecap: spec.stroke?.linecap ?? recipe.stroke.linecap,
        strokeLinejoin: spec.stroke?.linejoin ?? recipe.stroke.linejoin,
      }),
      ...(meta?.weight !== undefined ? { weight: meta.weight } : {}),
      ...(meta?.tags ? { tags: meta.tags } : {}),
    }
  }

  if (width === undefined || height === undefined) {
    throw new ComposeError(`Component "${name}" declares no variants.`)
  }

  return {
    width,
    height,
    variants,
    ...pickTransforms(spec),
  }
}

function buildInlineComponent(spec: Extract<ComponentSpec, { source: 'inline' }>): Component {
  return {
    width: spec.width,
    height: spec.height,
    variants: spec.variants,
    ...pickTransforms(spec),
  }
}

function pickTransforms(spec: ComponentSpec): Partial<Component> {
  return {
    ...(spec.probability !== undefined ? { probability: spec.probability } : {}),
    ...(spec.rotate ? { rotate: spec.rotate } : {}),
    ...(spec.scale ? { scale: spec.scale } : {}),
    ...(spec.translate ? { translate: spec.translate } : {}),
  }
}

function makeHelpers(recipe: Recipe, components: Record<string, Component>): CanvasHelpers {
  const sizeOf = (component: string) => {
    const resolved = components[component]
    if (!resolved) throw new ComposeError(`Canvas references unknown component "${component}".`)
    return { width: resolved.width, height: resolved.height }
  }

  return {
    canvas: recipe.canvas,
    sizeOf,
    place: (component, options = {}) => {
      const { width, height } = sizeOf(component)
      const {
        size = Math.min(recipe.canvas.width, recipe.canvas.height),
        cx = recipe.canvas.width / 2,
        cy = recipe.canvas.height / 2,
      } = options

      // Uniform scale keeps non-square artwork from stretching; the longer side fills `size`.
      const scale = size / Math.max(width, height)
      const x = cx - (width * scale) / 2
      const y = cy - (height * scale) / 2

      const element: Element = {
        type: 'component',
        name: component,
        attributes: { transform: `translate(${round(x)} ${round(y)}) scale(${round(scale)})` },
      }
      return element
    },
  }
}

/** Trims float noise so regenerating a definition produces a stable diff. */
function round(value: number): number {
  return Math.round(value * 1e4) / 1e4
}
